drone1:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  # Velocity Controllers ---------------------------------------
  jointFL_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: FL_joint_1
    pid: {p: 1.0, i: 0.01, d: 0.0}
  jointFR_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: FR_joint_1
    pid: {p: 1.0, i: 0.01, d: 0.0}
  jointBL_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: BL_joint_1
    pid: {p: 1.0, i: 0.01, d: 0.0}
  jointBR_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: BR_joint_1
    pid: {p: 1.0, i: 0.01, d: 0.0}

drone2:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  jointFL_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: FL_joint_2
    pid: {p: 1.0, i: 0.01, d: 0.0}
  jointFR_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: FR_joint_2
    pid: {p: 1.0, i: 0.01, d: 0.0}
  jointBL_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: BL_joint_2
    pid: {p: 1.0, i: 0.01, d: 0.0}
  jointBR_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: BR_joint_2
    pid: {p: 1.0, i: 0.01, d: 0.0}

