joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 20

# Velocity Controllers ---------------------------------------
joint1_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: FL_joint
  pid: {p: 1.0, i: 0.01, d: 0.0}
joint2_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: FR_joint
  pid: {p: 1.0, i: 0.01, d: 0.0}
joint3_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: BL_joint
  pid: {p: 1.0, i: 0.01, d: 0.0}
joint4_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: BR_joint
  pid: {p: 1.0, i: 0.01, d: 0.0}

